In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.model_selection import cross_val_score

In [3]:
data=pd.read_csv("/content/train.csv")
df=pd.DataFrame(data)
df.head()

,id,week,center_id,meal_id,checkout_price,base_price,emailer_for_promotion,homepage_featured,num_orders
0,1379560,1,55,1885,136.83,152.29,0,0,177
1,1466964,1,55,1993,136.83,135.83,0,0,270
2,1346989,1,55,2539,134.86,135.86,0,0,189
3,1338232,1,55,2139,339.50,437.53,0,0,54
4,1448490,1,55,2631,243.50,242.50,0,0,40

In [4]:
df.isnull().sum()

id                       0
week                     0
center_id                0
meal_id                  0
checkout_price           0
base_price               0
emailer_for_promotion    0
homepage_featured        0
num_orders               0
dtype: int64

In [5]:
df["discount"] = (df["base_price"] - df["checkout_price"])/df["base_price"]
df = pd.get_dummies(df, columns=["meal_id","center_id"])
df["promo_discount"] =df["discount"] * df["homepage_featured"]*df["emailer_for_promotion"]
x=df.drop(columns=["id","num_orders"],axis=1)
y=df["num_orders"]
print(x.head())
print(y.head())

   week  checkout_price  base_price  emailer_for_promotion  homepage_featured  \
0     1          136.83      152.29                      0                  0
1     1          136.83      135.83                      0                  0
2     1          134.86      135.86                      0                  0
3     1          339.50      437.53                      0                  0
4     1          243.50      242.50                      0                  0

   discount  meal_id_1062  meal_id_1109  meal_id_1198  meal_id_1207  ...  \
0  0.101517         False         False         False         False  ...
1 -0.007362         False         False         False         False  ...
2  0.007361         False         False         False         False  ...
3  0.224053         False         False         False         False  ...
4 -0.004124         False         False         False         False  ...

   center_id_149  center_id_152  center_id_153  center_id_157  center_id_161  \
0          False          False          False          False          False
1          False          False          False          False          False
2          False          False          False          False          False
3          False          False          False          False          False
4          False          False          False          False          False

   center_id_162  center_id_174  center_id_177  center_id_186  promo_discount
0          False          False          False          False             0.0
1          False          False          False          False            -0.0
2          False          False          False          False             0.0
3          False          False          False          False             0.0
4          False          False          False          False            -0.0

[5 rows x 135 columns]
0    177
1    270
2    189
3     54
4     40
Name: num_orders, dtype: int64

In [6]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
model=KNeighborsRegressor()
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
mse=mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)
print("Mean Squared Error:",mse)
print("R2 Score:",r2)

Mean Squared Error: 60785.45510108422
R2 Score: 0.6014943206027511

In [7]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(x_train)
X_test_scaled = scaler.transform(x_test)
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)
mse=mean_squared_error(y_test,y_pred)
r2=r2_score(y_test,y_pred)
print("Mean Squared Error:",mse)
print("R2 Score:",r2)

Mean Squared Error: 36875.08247990363
R2 Score: 0.7582492428156309

In [8]:
results = []

for k in [1,3,5,7,9,11,15,21]:
    knn = KNeighborsRegressor(n_neighbors=k)

    knn.fit(X_train_scaled, y_train)

    pred = knn.predict(X_test_scaled)

    results.append(
        (
            k,
            r2_score(y_test,pred)
        )
    )

print(results)

[(1, 0.7242567197187534), (3, 0.7612857717296271), (5, 0.7582492428156309), (7, 0.7523914072665293), (9, 0.7464229890056037), (11, 0.7395867470684283), (15, 0.7242197925003514), (21, 0.6995866194352423)]

In [9]:
print( knn.score(X_train_scaled,y_train))
print(
    knn.score(X_test_scaled,y_test)
)

0.7373364340422628
0.6995866194352423

In [10]:
#for other relationship graphs refer to linear regression model